/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1.sistemasoperativos;
import DataStructures.PCB;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
        // Color del background
    this.getContentPane().setBackground(new java.awt.Color(30, 30, 45));
    
    // Para que la consola también combine:
    txtConsola.setBackground(new java.awt.Color(20, 20, 30));
    
   
        // Redirigir la consola al JTextArea (txtConsola)
        java.io.PrintStream printStream = new java.io.PrintStream(new CustomOutputStream(txtConsola));
        System.setOut(printStream);
        System.setErr(printStream);
        
        // Timer: Actualiza la pantalla cada 200ms
        Timer timer = new Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizarInformacion();
            }
        });
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        tblListos1 = new javax.swing.JTable();
        lblReloj = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        lblAlgoritmoActual = new javax.swing.JLabel();
        cmbAlgoritmos = new javax.swing.JComboBox<>();
        btnCambiar = new javax.swing.JButton();
        btnInterrupcion = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblListos = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblTerminados = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblBloqueados = new javax.swing.JTable();
        sldVelocidad = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        lblModo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSuspendidos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btn20Procesos = new javax.swing.JButton();
        btnCargarCSV = new javax.swing.JButton();
        btnCargarJSON = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        tblListos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Status", "PC", "MAR", "Prioridad", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblListos1);
        if (tblListos1.getColumnModel().getColumnCount() > 0) {
            tblListos1.getColumnModel().getColumn(1).setResizable(false);
            tblListos1.getColumnModel().getColumn(2).setResizable(false);
            tblListos1.getColumnModel().getColumn(3).setResizable(false);
            tblListos1.getColumnModel().getColumn(4).setResizable(false);
            tblListos1.getColumnModel().getColumn(5).setResizable(false);
            tblListos1.getColumnModel().getColumn(6).setResizable(false);
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 45));

        lblReloj.setBackground(new java.awt.Color(0, 51, 102));
        lblReloj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblReloj.setForeground(new java.awt.Color(204, 204, 204));
        lblReloj.setText("Reloj: 0");
        lblReloj.setOpaque(true);

        lblCPU.setBackground(new java.awt.Color(204, 204, 255));
        lblCPU.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCPU.setForeground(new java.awt.Color(0, 0, 102));
        lblCPU.setText("CPU: IDLE");
        lblCPU.setOpaque(true);

        lblAlgoritmoActual.setBackground(new java.awt.Color(0, 51, 102));
        lblAlgoritmoActual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlgoritmoActual.setForeground(new java.awt.Color(204, 204, 204));
        lblAlgoritmoActual.setText("Algoritmo: FCFS");
        lblAlgoritmoActual.setOpaque(true);

        cmbAlgoritmos.setBackground(new java.awt.Color(102, 102, 255));
        cmbAlgoritmos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbAlgoritmos.setForeground(new java.awt.Color(204, 204, 204));
        cmbAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "Round Robin", "SRT", "Prioridad", "EDF" }));

        btnCambiar.setBackground(new java.awt.Color(102, 102, 255));
        btnCambiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCambiar.setForeground(new java.awt.Color(204, 204, 204));
        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(this::btnCambiarActionPerformed);

        btnInterrupcion.setBackground(new java.awt.Color(102, 102, 255));
        btnInterrupcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInterrupcion.setForeground(new java.awt.Color(204, 204, 204));
        btnInterrupcion.setText("Crear Interrupción");
        btnInterrupcion.addActionListener(this::btnInterrupcionActionPerformed);

        tblListos.setBackground(new java.awt.Color(153, 204, 255));
        tblListos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Status", "PC", "MAR", "Prioridad", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListos.setToolTipText("");
        jScrollPane6.setViewportView(tblListos);
        if (tblListos.getColumnModel().getColumnCount() > 0) {
            tblListos.getColumnModel().getColumn(1).setResizable(false);
            tblListos.getColumnModel().getColumn(2).setResizable(false);
            tblListos.getColumnModel().getColumn(3).setResizable(false);
            tblListos.getColumnModel().getColumn(4).setResizable(false);
            tblListos.getColumnModel().getColumn(5).setResizable(false);
            tblListos.getColumnModel().getColumn(6).setResizable(false);
        }

        tblTerminados.setBackground(new java.awt.Color(153, 204, 255));
        tblTerminados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Status", "PC", "MAR", "Prioridad", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(tblTerminados);
        if (tblTerminados.getColumnModel().getColumnCount() > 0) {
            tblTerminados.getColumnModel().getColumn(1).setResizable(false);
            tblTerminados.getColumnModel().getColumn(2).setResizable(false);
            tblTerminados.getColumnModel().getColumn(3).setResizable(false);
            tblTerminados.getColumnModel().getColumn(4).setResizable(false);
            tblTerminados.getColumnModel().getColumn(5).setResizable(false);
            tblTerminados.getColumnModel().getColumn(6).setResizable(false);
        }

        tblBloqueados.setBackground(new java.awt.Color(153, 204, 255));
        tblBloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Status", "PC", "MAR", "Prioridad", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(tblBloqueados);
        if (tblBloqueados.getColumnModel().getColumnCount() > 0) {
            tblBloqueados.getColumnModel().getColumn(1).setResizable(false);
            tblBloqueados.getColumnModel().getColumn(2).setResizable(false);
            tblBloqueados.getColumnModel().getColumn(3).setResizable(false);
            tblBloqueados.getColumnModel().getColumn(4).setResizable(false);
            tblBloqueados.getColumnModel().getColumn(5).setResizable(false);
            tblBloqueados.getColumnModel().getColumn(6).setResizable(false);
        }

        sldVelocidad.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        sldVelocidad.setMaximum(3000);
        sldVelocidad.setMinimum(100);
        sldVelocidad.setPaintLabels(true);
        sldVelocidad.setPaintTicks(true);
        sldVelocidad.setValue(1000);
        sldVelocidad.addChangeListener(this::sldVelocidadStateChanged);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("COLA DE TERMINADOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("COLA DE LISTOS");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("COLA DE BLOQUEADOS");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);

        txtConsola.setBackground(new java.awt.Color(0, 0, 0));
        txtConsola.setColumns(20);
        txtConsola.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtConsola.setForeground(new java.awt.Color(0, 255, 0));
        txtConsola.setRows(5);
        jScrollPane1.setViewportView(txtConsola);

        lblModo.setBackground(new java.awt.Color(0, 51, 102));
        lblModo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblModo.setForeground(new java.awt.Color(255, 0, 0));
        lblModo.setText("Modo: KERNEL");
        lblModo.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(0, 51, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Velocidad");
        jLabel4.setOpaque(true);

        tblSuspendidos.setBackground(new java.awt.Color(153, 204, 255));
        tblSuspendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Status", "PC", "MAR", "Prioridad", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSuspendidos);
        if (tblSuspendidos.getColumnModel().getColumnCount() > 0) {
            tblSuspendidos.getColumnModel().getColumn(0).setResizable(false);
            tblSuspendidos.getColumnModel().getColumn(1).setResizable(false);
            tblSuspendidos.getColumnModel().getColumn(2).setResizable(false);
            tblSuspendidos.getColumnModel().getColumn(3).setResizable(false);
            tblSuspendidos.getColumnModel().getColumn(4).setResizable(false);
            tblSuspendidos.getColumnModel().getColumn(5).setResizable(false);
            tblSuspendidos.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("COLA DE SUSPENDIDOS (Disco)");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);

        btn20Procesos.setBackground(new java.awt.Color(102, 102, 255));
        btn20Procesos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn20Procesos.setForeground(new java.awt.Color(204, 204, 204));
        btn20Procesos.setText("+ 20 Procesos Aleatorios");
        btn20Procesos.addActionListener(this::btn20ProcesosActionPerformed);

        btnCargarCSV.setBackground(new java.awt.Color(102, 102, 255));
        btnCargarCSV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCargarCSV.setForeground(new java.awt.Color(204, 204, 204));
        btnCargarCSV.setText("Cargar CSV");
        btnCargarCSV.addActionListener(this::btnCargarCSVActionPerformed);

        btnCargarJSON.setBackground(new java.awt.Color(102, 102, 255));
        btnCargarJSON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCargarJSON.setForeground(new java.awt.Color(204, 204, 204));
        btnCargarJSON.setText("Cargar JSON");
        btnCargarJSON.addActionListener(this::btnCargarJSONActionPerformed);

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("LOG DE ESTADOS");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                        .addComponent(lblCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblModo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(sldVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                        .addComponent(lblAlgoritmoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCambiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnInterrupcion))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn20Procesos)
                        .addGap(18, 18, 18)
                        .addComponent(btnCargarCSV)
                        .addGap(18, 18, 18)
                        .addComponent(btnCargarJSON))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblCPU))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCambiar)
                                    .addComponent(btnInterrupcion)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReloj)
                            .addComponent(lblModo))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(sldVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlgoritmoActual)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn20Procesos)
                                .addComponent(btnCargarCSV)
                                .addComponent(btnCargarJSON)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
String seleccion = cmbAlgoritmos.getSelectedItem().toString();
    Proyecto1SistemasOperativos.Algoritmo alg = Proyecto1SistemasOperativos.Algoritmo.FCFS;

    switch (seleccion) {
        case "FCFS" -> alg = Proyecto1SistemasOperativos.Algoritmo.FCFS;
        case "Round Robin" -> alg = Proyecto1SistemasOperativos.Algoritmo.ROUND_ROBIN;
        case "SRT" -> alg = Proyecto1SistemasOperativos.Algoritmo.SRT;
        case "Prioridad" -> alg = Proyecto1SistemasOperativos.Algoritmo.PRIORIDAD;
        case "EDF" -> alg = Proyecto1SistemasOperativos.Algoritmo.EDF;
    }

    Proyecto1SistemasOperativos.scheduler.cambiarAlgoritmo(alg);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnInterrupcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterrupcionActionPerformed
int id = (int)(Math.random() * 1000);
    // (id, nombre, instrucciones, prioridad, deadline, arrival, etc)
    PCB nuevo = new PCB("INT-" + id, "Interrupcion", 15, 1, 30, Proyecto1SistemasOperativos.globalClock, 3);

    try {
        Proyecto1SistemasOperativos.mutexReady.acquire();
        // Insertamos inteligentemente según el algoritmo actual
        switch (Proyecto1SistemasOperativos.algoritmoActual) {
            case PRIORIDAD -> Proyecto1SistemasOperativos.readyQueue.insertByPriority(nuevo);
            case SRT -> Proyecto1SistemasOperativos.readyQueue.insertBySRT(nuevo);
            case EDF -> Proyecto1SistemasOperativos.readyQueue.insertByDeadline(nuevo);
            default -> Proyecto1SistemasOperativos.readyQueue.addLast(nuevo);
        }
        Proyecto1SistemasOperativos.mutexReady.release();
        JOptionPane.showMessageDialog(this, "¡Proceso Creado!");
    } catch (Exception ex) { ex.printStackTrace(); }
    }//GEN-LAST:event_btnInterrupcionActionPerformed

    private void sldVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVelocidadStateChanged
// Actualizamos la variable global con el valor que elija el usuario en la barra
Proyecto1SistemasOperativos.velocidadSimulacion = sldVelocidad.getValue();        // TODO add your handling code here:
    }//GEN-LAST:event_sldVelocidadStateChanged

    private void btn20ProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ProcesosActionPerformed
        try {
        // 1. Bloqueamos la cola de listos para evitar inconsistencias con el CPU
        Proyecto1SistemasOperativos.mutexReady.acquire();
        
        // 2. Generamos los 20 procesos
        for (int i = 0; i < 20; i++) {
            int idAleatorio = (int) (Math.random() * 10000);
            int inst = 10 + (int) (Math.random() * 21); // Instrucciones entre 10 y 30
            int prio = 1 + (int) (Math.random() * 3);   // Prioridad entre 1 y 3
            
            // Deadline a futuro basado en el reloj actual
            int dline = Proyecto1SistemasOperativos.globalClock + 50 + (int) (Math.random() * 51); 
            
            // Creamos el PCB con tu constructor
            PCB nuevoProceso = new PCB("P" + idAleatorio, "Mision_Rnd", inst, prio, dline, 5, 3);
            
            // 3. Insertamos respetando el algoritmo actual
            switch (Proyecto1SistemasOperativos.algoritmoActual) {
                case PRIORIDAD -> Proyecto1SistemasOperativos.readyQueue.insertByPriority(nuevoProceso);
                case SRT -> Proyecto1SistemasOperativos.readyQueue.insertBySRT(nuevoProceso);
                case EDF -> Proyecto1SistemasOperativos.readyQueue.insertByDeadline(nuevoProceso);
                default -> Proyecto1SistemasOperativos.readyQueue.addLast(nuevoProceso);
            }
        }
        
        // 4. Soltamos el semáforo para que el Scheduler siga trabajando
        Proyecto1SistemasOperativos.mutexReady.release();
        
        System.out.println("> 20 Procesos aleatorios inyectados a la RAM exitosamente.");
        
    } catch (Exception ex) { 
        System.err.println("Error al inyectar procesos: " + ex.getMessage());
    }
    }//GEN-LAST:event_btn20ProcesosActionPerformed

    private void btnCargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCSVActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo CSV");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV (*.csv)", "csv"));

        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();
            
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
                String linea;
                boolean primeraLinea = true; // Para saltar los encabezados si los hay
                
                Proyecto1SistemasOperativos.mutexReady.acquire(); // Bloqueamos la cola
                
                while ((linea = br.readLine()) != null) {
                    if (primeraLinea) {
                        primeraLinea = false;
                        continue; // Saltamos la primera línea de encabezados
                    }
                    
                    String[] datos = linea.split(","); // Separamos por coma
                    if (datos.length >= 4) {
                        // Asumiendo el orden: nombre, instrucciones, prioridad, deadline
                        String nombre = datos[0].trim();
                        int inst = Integer.parseInt(datos[1].trim());
                        int prio = Integer.parseInt(datos[2].trim());
                        int dline = Integer.parseInt(datos[3].trim());
                        
                        int idAleatorio = (int) (Math.random() * 10000);
                        
                        // Creamos el proceso (ajusta los últimos números si tu constructor es distinto)
                        PCB nuevoProceso = new PCB("P" + idAleatorio, nombre, inst, prio, dline, 5, 3);
                        
                        // Insertamos según el algoritmo actual
                        switch (Proyecto1SistemasOperativos.algoritmoActual) {
                            case PRIORIDAD -> Proyecto1SistemasOperativos.readyQueue.insertByPriority(nuevoProceso);
                            case SRT -> Proyecto1SistemasOperativos.readyQueue.insertBySRT(nuevoProceso);
                            case EDF -> Proyecto1SistemasOperativos.readyQueue.insertByDeadline(nuevoProceso);
                            default -> Proyecto1SistemasOperativos.readyQueue.addLast(nuevoProceso);
                        }
                    }
                }
                Proyecto1SistemasOperativos.mutexReady.release(); // Soltamos la cola
                
                javax.swing.JOptionPane.showMessageDialog(this, "CSV cargado exitosamente.");
                System.out.println("> Procesos del CSV inyectados a la RAM.");
                
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al leer el CSV: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarCSVActionPerformed

    private void btnCargarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarJSONActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo JSON");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos JSON (*.json)", "json"));

        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();
            
            try {
                // LEER EL ARCHIVO COMO TEXTO COMPLETO
                String contenido = new String(java.nio.file.Files.readAllBytes(archivo.toPath()));
                
                // NOTA: Este bloque usa la librería 'org.json'. 
                // Necesitas tenerla instalada en tu proyecto (dependencia Maven/Gradle o el archivo .jar)
                org.json.JSONArray arregloJson = new org.json.JSONArray(contenido);
                
                Proyecto1SistemasOperativos.mutexReady.acquire(); // Bloqueamos la cola
                
                for (int i = 0; i < arregloJson.length(); i++) {
                    org.json.JSONObject obj = arregloJson.getJSONObject(i);
                    
                    String nombre = obj.getString("nombre");
                    int inst = obj.getInt("instrucciones");
                    int prio = obj.getInt("prioridad");
                    int dline = obj.getInt("deadline");
                    
                    int idAleatorio = (int) (Math.random() * 10000);
                    
                    // Creamos el proceso
                    PCB nuevoProceso = new PCB("P" + idAleatorio, nombre, inst, prio, dline, 5, 3);
                    
                    // Insertamos según el algoritmo actual
                    switch (Proyecto1SistemasOperativos.algoritmoActual) {
                        case PRIORIDAD -> Proyecto1SistemasOperativos.readyQueue.insertByPriority(nuevoProceso);
                        case SRT -> Proyecto1SistemasOperativos.readyQueue.insertBySRT(nuevoProceso);
                        case EDF -> Proyecto1SistemasOperativos.readyQueue.insertByDeadline(nuevoProceso);
                        default -> Proyecto1SistemasOperativos.readyQueue.addLast(nuevoProceso);
                    }
                }
                
                Proyecto1SistemasOperativos.mutexReady.release(); // Soltamos la cola
                javax.swing.JOptionPane.showMessageDialog(this, "JSON cargado exitosamente.");
                System.out.println("> Procesos del JSON inyectados a la RAM.");
                
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al leer el JSON: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarJSONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn20Procesos;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnCargarJSON;
    private javax.swing.JButton btnInterrupcion;
    private javax.swing.JComboBox<String> cmbAlgoritmos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblAlgoritmoActual;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblModo;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JSlider sldVelocidad;
    private javax.swing.JTable tblBloqueados;
    private javax.swing.JTable tblListos;
    private javax.swing.JTable tblListos1;
    private javax.swing.JTable tblSuspendidos;
    private javax.swing.JTable tblTerminados;
    private javax.swing.JTextArea txtConsola;
    // End of variables declaration//GEN-END:variables

    private void actualizarInformacion() {
            // 1. Reloj
            lblReloj.setText("Reloj: " + Proyecto1SistemasOperativos.globalClock);

            // 2. CPU y Modo
            PCB p = Proyecto1SistemasOperativos.runningProcess;
            if (p != null) {
                lblCPU.setText("CPU: " + p.getNombre() + " (ID:" + p.getId() + ")");
                lblModo.setText("MODO: USUARIO"); // El CPU está ocupado por un proceso
                lblModo.setForeground(new java.awt.Color(0, 153, 0)); // Verde
            } else {
                lblCPU.setText("CPU: IDLE");
                lblModo.setText("MODO: KERNEL"); // El OS está buscando qué hacer
                lblModo.setForeground(java.awt.Color.RED); // Rojo o Azul
            }

            // 3. Algoritmo
            lblAlgoritmoActual.setText("Algoritmo: " + Proyecto1SistemasOperativos.algoritmoActual);

            // 4. Colas (Ahora usando JTables en lugar de TextAreas)

            // --- COLA DE LISTOS ---
            if (Proyecto1SistemasOperativos.mutexReady.tryAcquire()) {
                DefaultTableModel modeloListos = (DefaultTableModel) tblListos.getModel();
                modeloListos.setRowCount(0); // Esto limpia la tabla antes de reescribirla

                for (int i = 0; i < Proyecto1SistemasOperativos.readyQueue.getSize(); i++) {
                    PCB pcb = Proyecto1SistemasOperativos.readyQueue.get(i);
                    modeloListos.addRow(new Object[]{
                        pcb.getId(), pcb.getNombre(), pcb.getStatus(), 
                        pcb.getPc(), pcb.getMar(), pcb.getPrioridad(), pcb.getDeadline()
                    });
                }
                Proyecto1SistemasOperativos.mutexReady.release();
            }

            // --- COLA DE BLOQUEADOS ---
            if (Proyecto1SistemasOperativos.mutexBlocked.tryAcquire()) {
                DefaultTableModel modeloBloqueados = (DefaultTableModel) tblBloqueados.getModel();
                modeloBloqueados.setRowCount(0);

                for (int i = 0; i < Proyecto1SistemasOperativos.blockedQueue.getSize(); i++) {
                    PCB pcb = Proyecto1SistemasOperativos.blockedQueue.get(i);
                    modeloBloqueados.addRow(new Object[]{
                        pcb.getId(), pcb.getNombre(), pcb.getStatus(), 
                        pcb.getPc(), pcb.getMar(), pcb.getPrioridad(), pcb.getDeadline()
                    });
                }
                Proyecto1SistemasOperativos.mutexBlocked.release();
            }

            // --- COLA DE TERMINADOS ---
            DefaultTableModel modeloTerminados = (DefaultTableModel) tblTerminados.getModel();
            modeloTerminados.setRowCount(0);

            for (int i = 0; i < Proyecto1SistemasOperativos.finishedQueue.getSize(); i++) {
                PCB pcb = Proyecto1SistemasOperativos.finishedQueue.get(i);
                modeloTerminados.addRow(new Object[]{
                    pcb.getId(), pcb.getNombre(), pcb.getStatus(), 
                    pcb.getPc(), pcb.getMar(), pcb.getPrioridad(), pcb.getDeadline()
                });
            }

            // --- COLA DE SUSPENDIDOS (Listos-Suspendidos + Bloqueados-Suspendidos) ---
            if (Proyecto1SistemasOperativos.mutexSuspended.tryAcquire()) {
                DefaultTableModel modeloSuspendidos = (DefaultTableModel) tblSuspendidos.getModel();
                modeloSuspendidos.setRowCount(0); // Limpiamos la tabla

                // 1. Mostramos los procesos en Listo-Suspendido
                for (int i = 0; i < Proyecto1SistemasOperativos.readySuspendedQueue.getSize(); i++) {
                    PCB pcb = Proyecto1SistemasOperativos.readySuspendedQueue.get(i);
                    modeloSuspendidos.addRow(new Object[]{
                        pcb.getId(), pcb.getNombre(), pcb.getStatus(), 
                        pcb.getPc(), pcb.getMar(), pcb.getPrioridad(), pcb.getDeadline()
                    });
                }

                Proyecto1SistemasOperativos.mutexSuspended.release();
            }
    } // FIN DEL MÉTODO actualizarInformacion()

    // CLASE PARA LA CONSOLA
    class CustomOutputStream extends java.io.OutputStream {
        private javax.swing.JTextArea textArea;

        public CustomOutputStream(javax.swing.JTextArea textArea) {
            this.textArea = textArea;
        }

        @Override
        public void write(int b) {
            // Escribe el texto en el JTextArea
            textArea.append(String.valueOf((char)b));
            // Hace que el scroll baje automáticamente para ver el texto más reciente
            textArea.setCaretPosition(textArea.getDocument().getLength());
        }
    }

}