/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1.sistemasoperativos;
import DataStructures.PCB;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
   public Dashboard() {
        initComponents();
        
        // Redirigir la consola al JTextArea (txtConsola)
        java.io.PrintStream printStream = new java.io.PrintStream(new CustomOutputStream(txtConsola));
        System.setOut(printStream);
        System.setErr(printStream);
        
        // Timer: Actualiza la pantalla cada 200ms
        Timer timer = new Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizarInformacion();
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        tblListos1 = new javax.swing.JTable();
        lblReloj = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        lblAlgoritmoActual = new javax.swing.JLabel();
        cmbAlgoritmos = new javax.swing.JComboBox<>();
        btnCambiar = new javax.swing.JButton();
        btnInterrupcion = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblListos = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblTerminados = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblBloqueados = new javax.swing.JTable();
        sldVelocidad = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblModo = new javax.swing.JLabel();

        tblListos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Status", "PC", "MAR", "Prioridad", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblListos1);
        if (tblListos1.getColumnModel().getColumnCount() > 0) {
            tblListos1.getColumnModel().getColumn(1).setResizable(false);
            tblListos1.getColumnModel().getColumn(2).setResizable(false);
            tblListos1.getColumnModel().getColumn(3).setResizable(false);
            tblListos1.getColumnModel().getColumn(4).setResizable(false);
            tblListos1.getColumnModel().getColumn(5).setResizable(false);
            tblListos1.getColumnModel().getColumn(6).setResizable(false);
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReloj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReloj.setText("Reloj: 0");

        lblCPU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCPU.setText("CPU: IDLE");

        lblAlgoritmoActual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlgoritmoActual.setText("Algoritmo: FCFS");

        cmbAlgoritmos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "Round Robin", "SRT", "Prioridad", "EDF" }));

        btnCambiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(this::btnCambiarActionPerformed);

        btnInterrupcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInterrupcion.setText("Crear Interrupción");
        btnInterrupcion.addActionListener(this::btnInterrupcionActionPerformed);

        tblListos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Status", "PC", "MAR", "Prioridad", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListos.setToolTipText("");
        jScrollPane6.setViewportView(tblListos);
        if (tblListos.getColumnModel().getColumnCount() > 0) {
            tblListos.getColumnModel().getColumn(1).setResizable(false);
            tblListos.getColumnModel().getColumn(2).setResizable(false);
            tblListos.getColumnModel().getColumn(3).setResizable(false);
            tblListos.getColumnModel().getColumn(4).setResizable(false);
            tblListos.getColumnModel().getColumn(5).setResizable(false);
            tblListos.getColumnModel().getColumn(6).setResizable(false);
        }

        tblTerminados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Status", "PC", "MAR", "Prioridad", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(tblTerminados);
        if (tblTerminados.getColumnModel().getColumnCount() > 0) {
            tblTerminados.getColumnModel().getColumn(1).setResizable(false);
            tblTerminados.getColumnModel().getColumn(2).setResizable(false);
            tblTerminados.getColumnModel().getColumn(3).setResizable(false);
            tblTerminados.getColumnModel().getColumn(4).setResizable(false);
            tblTerminados.getColumnModel().getColumn(5).setResizable(false);
            tblTerminados.getColumnModel().getColumn(6).setResizable(false);
        }

        tblBloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Status", "PC", "MAR", "Prioridad", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(tblBloqueados);
        if (tblBloqueados.getColumnModel().getColumnCount() > 0) {
            tblBloqueados.getColumnModel().getColumn(1).setResizable(false);
            tblBloqueados.getColumnModel().getColumn(2).setResizable(false);
            tblBloqueados.getColumnModel().getColumn(3).setResizable(false);
            tblBloqueados.getColumnModel().getColumn(4).setResizable(false);
            tblBloqueados.getColumnModel().getColumn(5).setResizable(false);
            tblBloqueados.getColumnModel().getColumn(6).setResizable(false);
        }

        sldVelocidad.setMaximum(3000);
        sldVelocidad.setMinimum(100);
        sldVelocidad.setPaintLabels(true);
        sldVelocidad.setPaintTicks(true);
        sldVelocidad.setValue(1000);
        sldVelocidad.addChangeListener(this::sldVelocidadStateChanged);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("COLA DE TERMINADOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("COLA DE LISTOS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("COLA DE BLOQUEADOS");

        txtConsola.setBackground(new java.awt.Color(0, 0, 0));
        txtConsola.setColumns(20);
        txtConsola.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtConsola.setForeground(new java.awt.Color(0, 255, 0));
        txtConsola.setRows(5);
        jScrollPane1.setViewportView(txtConsola);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("LOG DE EVENTOS");

        lblModo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblModo.setForeground(new java.awt.Color(255, 0, 0));
        lblModo.setText("Modo: KERNEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnCambiar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(lblCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlgoritmoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInterrupcion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPU)
                    .addComponent(lblReloj, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAlgoritmoActual)
                        .addComponent(sldVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblModo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCambiar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnInterrupcion)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
String seleccion = cmbAlgoritmos.getSelectedItem().toString();
    Proyecto1SistemasOperativos.Algoritmo alg = Proyecto1SistemasOperativos.Algoritmo.FCFS;

    switch (seleccion) {
        case "FCFS" -> alg = Proyecto1SistemasOperativos.Algoritmo.FCFS;
        case "Round Robin" -> alg = Proyecto1SistemasOperativos.Algoritmo.ROUND_ROBIN;
        case "SRT" -> alg = Proyecto1SistemasOperativos.Algoritmo.SRT;
        case "Prioridad" -> alg = Proyecto1SistemasOperativos.Algoritmo.PRIORIDAD;
        case "EDF" -> alg = Proyecto1SistemasOperativos.Algoritmo.EDF;
    }

    Proyecto1SistemasOperativos.scheduler.cambiarAlgoritmo(alg);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnInterrupcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterrupcionActionPerformed
int id = (int)(Math.random() * 1000);
    // (id, nombre, instrucciones, prioridad, deadline, arrival, etc)
    PCB nuevo = new PCB("INT-" + id, "Interrupcion", 15, 1, 30, Proyecto1SistemasOperativos.globalClock, 3);

    try {
        Proyecto1SistemasOperativos.mutexReady.acquire();
        // Insertamos inteligentemente según el algoritmo actual
        switch (Proyecto1SistemasOperativos.algoritmoActual) {
            case PRIORIDAD -> Proyecto1SistemasOperativos.readyQueue.insertByPriority(nuevo);
            case SRT -> Proyecto1SistemasOperativos.readyQueue.insertBySRT(nuevo);
            case EDF -> Proyecto1SistemasOperativos.readyQueue.insertByDeadline(nuevo);
            default -> Proyecto1SistemasOperativos.readyQueue.addLast(nuevo);
        }
        Proyecto1SistemasOperativos.mutexReady.release();
        JOptionPane.showMessageDialog(this, "¡Proceso Creado!");
    } catch (Exception ex) { ex.printStackTrace(); }
    }//GEN-LAST:event_btnInterrupcionActionPerformed

    private void sldVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVelocidadStateChanged
// Actualizamos la variable global con el valor que elija el usuario en la barra
Proyecto1SistemasOperativos.velocidadSimulacion = sldVelocidad.getValue();        // TODO add your handling code here:
    }//GEN-LAST:event_sldVelocidadStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnInterrupcion;
    private javax.swing.JComboBox<String> cmbAlgoritmos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblAlgoritmoActual;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblModo;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JSlider sldVelocidad;
    private javax.swing.JTable tblBloqueados;
    private javax.swing.JTable tblListos;
    private javax.swing.JTable tblListos1;
    private javax.swing.JTable tblTerminados;
    private javax.swing.JTextArea txtConsola;
    // End of variables declaration//GEN-END:variables

    private void actualizarInformacion() {
        // 1. Reloj
        lblReloj.setText("Reloj: " + Proyecto1SistemasOperativos.globalClock);

        // 2. CPU y Modo
        PCB p = Proyecto1SistemasOperativos.runningProcess;
        if (p != null) {
            lblCPU.setText("CPU: " + p.getNombre() + " (ID:" + p.getId() + ")");
            lblModo.setText("MODO: USUARIO"); // El CPU está ocupado por un proceso
            lblModo.setForeground(new java.awt.Color(0, 153, 0)); // Verde
        } else {
            lblCPU.setText("CPU: IDLE");
            lblModo.setText("MODO: KERNEL"); // El OS está buscando qué hacer
            lblModo.setForeground(java.awt.Color.RED); // Rojo o Azul
        }

        // 3. Algoritmo
        lblAlgoritmoActual.setText("Algoritmo: " + Proyecto1SistemasOperativos.algoritmoActual);

        // 4. Colas (Ahora usando JTables en lugar de TextAreas)

        // --- COLA DE LISTOS ---
        if (Proyecto1SistemasOperativos.mutexReady.tryAcquire()) {
            DefaultTableModel modeloListos = (DefaultTableModel) tblListos.getModel();
            modeloListos.setRowCount(0); // Esto limpia la tabla antes de reescribirla

            // NOTA: Ajusta ".getSize()" y ".get(i)" según como se llamen en tu clase de Colas
            for (int i = 0; i < Proyecto1SistemasOperativos.readyQueue.getSize(); i++) {
                PCB pcb = Proyecto1SistemasOperativos.readyQueue.get(i);
                modeloListos.addRow(new Object[]{
                    pcb.getId(), pcb.getNombre(), pcb.getStatus(), 
                    pcb.getPc(), pcb.getMar(), pcb.getPrioridad(), pcb.getDeadline()
                });
            }
            Proyecto1SistemasOperativos.mutexReady.release();
        }

        // --- COLA DE BLOQUEADOS ---
        if (Proyecto1SistemasOperativos.mutexBlocked.tryAcquire()) {
            DefaultTableModel modeloBloqueados = (DefaultTableModel) tblBloqueados.getModel();
            modeloBloqueados.setRowCount(0);

            for (int i = 0; i < Proyecto1SistemasOperativos.blockedQueue.getSize(); i++) {
                PCB pcb = Proyecto1SistemasOperativos.blockedQueue.get(i);
                modeloBloqueados.addRow(new Object[]{
                    pcb.getId(), pcb.getNombre(), pcb.getStatus(), 
                    pcb.getPc(), pcb.getMar(), pcb.getPrioridad(), pcb.getDeadline()
                });
            }
            Proyecto1SistemasOperativos.mutexBlocked.release();
        }

        // --- COLA DE TERMINADOS ---
        DefaultTableModel modeloTerminados = (DefaultTableModel) tblTerminados.getModel();
        modeloTerminados.setRowCount(0);

        for (int i = 0; i < Proyecto1SistemasOperativos.finishedQueue.getSize(); i++) {
            PCB pcb = Proyecto1SistemasOperativos.finishedQueue.get(i);
            modeloTerminados.addRow(new Object[]{
                pcb.getId(), pcb.getNombre(), pcb.getStatus(), 
                pcb.getPc(), pcb.getMar(), pcb.getPrioridad(), pcb.getDeadline()
            });
        }
    }
    // --- CLASE MÁGICA PARA REDIRIGIR LA CONSOLA ---
    class CustomOutputStream extends java.io.OutputStream {
        private javax.swing.JTextArea textArea;

        public CustomOutputStream(javax.swing.JTextArea textArea) {
            this.textArea = textArea;
        }

        @Override
        public void write(int b) {
            // Escribe el texto en el JTextArea
            textArea.append(String.valueOf((char)b));
            // Hace que el scroll baje automáticamente para ver el texto más reciente
            textArea.setCaretPosition(textArea.getDocument().getLength());
        }
    }
}
